[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/auth/*"
  to = "http://18.222.164.135:3000/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/players/*"
  to = "http://18.222.164.135:3000/players/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
